stages:
  - build-ci-image
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .cargo/registry
    - .cargo/git
    - src-tauri/target
  fallback_keys:
    - main

variables:
  CARGO_HOME: "$CI_PROJECT_DIR/.cargo"
  RUSTUP_HOME: "$CI_PROJECT_DIR/.rustup"
  npm_config_cache: "$CI_PROJECT_DIR/.npm"

build:ci-image:
  stage: build-ci-image
  image: docker:27
  services:
    - docker:27-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: on_success
    - when: never

  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -f Dockerfile.ci -t "$CI_REGISTRY_IMAGE/ci/linux-builder:latest" .
    - docker push "$CI_REGISTRY_IMAGE/ci/linux-builder:latest"

build:linux:
  stage: build
  image: $CI_REGISTRY_IMAGE/ci/linux-builder:latest
  script:
    - mise install
    - npm ci
    - npm run tauri build
  artifacts:
    when: always
    expire_in: 14 days
    paths:
      - src-tauri/target/release/bundle/
