stages:
  - build-ci-image
  - build

cache:
  key:
    files:
      - pnpm-lock.yaml
      - src-tauri/Cargo.lock
    prefix: ${CI_PROJECT_NAME}
  paths:
    - node_modules/
    - .pnpm-store/
    - .cargo/registry
    - .cargo/git
    - .rustup/
    - src-tauri/target
  policy: pull-push
  fallback_keys:
    - ${CI_PROJECT_NAME}
    - main

variables:
  CARGO_HOME: "$CI_PROJECT_DIR/.cargo"
  CARGO_TARGET_DIR: "$CI_PROJECT_DIR/src-tauri/target"
  RUSTUP_HOME: "$CI_PROJECT_DIR/.rustup"
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  PNPM_STORE_DIR: "$CI_PROJECT_DIR/.pnpm-store"

build:ci-image:
  stage: build-ci-image
  image: docker:27
  services:
    - docker:27-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: on_success
    - when: never

  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -f Dockerfile.ci -t "$CI_REGISTRY_IMAGE/ci/linux-builder:latest" .
    - docker push "$CI_REGISTRY_IMAGE/ci/linux-builder:latest"

build:linux:
  stage: build
  image: $CI_REGISTRY_IMAGE/ci/linux-builder:latest
  before_script:
    - mise activate --shell bash >> ~/.bashrc
  script:
    - mise install
    - mise init
    - mise lint
    - mise test
    - mise build
  artifacts:
    when: always
    expire_in: 14 days
    paths:
      - src-tauri/target/release/bundle/
