providers:
  - type: gitlab
    token:
      # Load GITLAB_TOKEN from environment variable
      env: GITLAB_TOKEN
    repos:
      # Show only the main branch of my pmon repository.
      # More are not supported yet.
      - name: nknapp/pmon
        main_branch: main
